# Generated by Django 3.1.7 on 2021-04-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.FilePathField(path='/Users/Juan/Documents/Django/mywebsite/staticfiles/images/'),
        ),
    ]
