# Generated by Django 3.1.7 on 2021-04-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_projeto_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='imagem',
        ),
    ]
